workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: python:3.12.4

before_script:
  - pip install poetry==1.8
  - poetry config virtualenvs.create false
  - poetry install



stages:
#  - build
  - test
#  - deploy

preparation:
  stage: test
  script:
    - python3 --version
    - pip --version
    - poetry --version
    - poetry show --tree
    - pytest --version


mypy:
  stage: test
  script:
    - mypy -p src

black:
  stage: test
  script:
    - black --check ./src
    - black --check ./tests

isort:
  stage: test
  script:
    - isort --profile "black" --filter-files ./src
    - isort --profile "black" --filter-files ./tests

flake8:
  stage: test
  script:
    - flake8 ./src/
    - flake8 ./tests/

test:
  stage: test
  script:
    - pytest --cov=src --cov-report=term-missing --cov-report=xml:coverage.xml --junitxml=report.xml
    - pip install coverage-badge
    - coverage-badge -o coverage.svg -f
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - coverage.svg
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
